In [276]:
import numpy as np

In [277]:
import pandas as pd

In [278]:
movies= pd.read_csv("Dataset/tmdb_5000_movies.csv")

In [279]:
credits=pd.read_csv("Dataset/tmdb_5000_credits.csv")

In [280]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [281]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [282]:
movies=movies.merge(credits,on='title')

In [283]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [284]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [285]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [286]:
##preprocessing

In [287]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [288]:
movies.dropna(inplace=True)

In [289]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [290]:
movies.duplicated().sum()

0

In [291]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [292]:
import ast

In [293]:
def  convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [294]:
movies['genres']=movies['genres'].apply(convert)

In [295]:
movies['keywords']=movies['keywords'].apply(convert)

In [296]:
def  convertname(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3 :
           L.append(i['name'])
           counter=counter+1
        else:
            break
    return L

In [297]:
movies['cast']=movies['cast'].apply(convertname)

In [298]:
movies['cast']

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [299]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [300]:
def  fetchdirectorname(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Editor':
            L.append(i['name'])
            break
    return L

In [301]:
movies['crew']=movies['crew'].apply(fetchdirectorname)

In [302]:
movies['crew'][0]

['Stephen E. Rivkin']

In [303]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [304]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [305]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[Stephen E. Rivkin]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Stephen E. Rivkin]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Lee Smith]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Lee Smith]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Eric Zumbrunnen]

In [310]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [312]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[StephenE.Rivkin]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[StephenE.Rivkin]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[LeeSmith]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[LeeSmith]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[EricZumbrunnen]

In [313]:
movies['tag']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [314]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[StephenE.Rivkin],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[StephenE.Rivkin],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[LeeSmith],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[LeeSmith],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[EricZumbrunnen],"[John, Carter, is, a, war-weary,, former, mili..."

In [335]:
new_df= movies[['movie_id','title','tag']]

In [336]:
new_df

,movie_id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [337]:
new_df['tag'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tag, Length: 4806, dtype: object

In [338]:
new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

C:\Users\Asus\AppData\Local\Temp\ipykernel_4920\4079141722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:" ".join(x))

In [339]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [341]:
new_df['tag'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenE.Rivkin'

In [342]:
new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

C:\Users\Asus\AppData\Local\Temp\ipykernel_4920\2231764002.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tag']=new_df['tag'].apply(lambda x:x.lower())

In [343]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [366]:
!pip install nltk
import nltk

Requirement already satisfied: nltk in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from nltk) (4.66.1)
Requirement already satisfied: colorama in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from click->nltk) (0.4.6)

In [378]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [379]:
from sklearn.feature_extraction.text import CountVectorizer

In [380]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [381]:
new_df['tag'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tag, Length: 4806, dtype: object

In [382]:
ps.stem('reading')

'read'

In [383]:
cv=CountVectorizer(max_features=5000,stop_words="english")

In [393]:
vectors=cv.fit_transform(new_df['tag']).toarray()

In [394]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [395]:
from sklearn.metrics.pairwise import cosine_similarity

In [397]:
similarity=cosine_similarity(vectors)

In [415]:
sorted(similarity[0],reverse=True)

[1.0,
 0.2537477434955704,
 0.25112360116696136,
 0.24165612634006073,
 0.24127175179050325,
 0.2372894989381248,
 0.23692415692169538,
 0.23621543814299706,
 0.23485569615051038,
 0.2324952774876386,
 0.22305671869347438,
 0.21621621621621623,
 0.21586644588817278,
 0.21582051197002577,
 0.2152488010002526,
 0.21369687880543226,
 0.2113701265354594,
 0.21059925059706258,
 0.21059925059706258,
 0.21049133398705727,
 0.21029989116983447,
 0.21029989116983447,
 0.2101050788156825,
 0.2071841649822589,
 0.20668850837512243,
 0.20668850837512243,
 0.20549873413169661,
 0.20134681656420733,
 0.20134681656420733,
 0.20032733246124987,
 0.19727878476642874,
 0.1934477640657483,
 0.1934477640657483,
 0.1926263261127128,
 0.18983159915049982,
 0.18944220058835154,
 0.1891891891891892,
 0.18857857160117855,
 0.18857857160117855,
 0.18790823039834775,
 0.18788455692040834,
 0.18668326147193276,
 0.18641092980036,
 0.18380365552345193,
 0.18316875326179907,
 0.18065550087085797,
 0.17972365808708388,
 0.17972365808708385,
 0.17757120130114434,
 0.17757120130114434,
 0.17684493567566834,
 0.17574991006549873,
 0.1752499093081954,
 0.1743714581157289,
 0.17170914210964275,
 0.17155007848855516,
 0.17139779254776524,
 0.16967515794730187,
 0.16916516233038026,
 0.16839306718964578,
 0.1677890138035061,
 0.1643989873053573,
 0.1643989873053573,
 0.1643989873053573,
 0.16439898730535726,
 0.16439898730535726,
 0.16312947805723718,
 0.16120647005479025,
 0.16120647005479025,
 0.15958626340564364,
 0.15949044456578,
 0.15819299929208316,
 0.15819299929208316,
 0.15794943794779692,
 0.15794943794779692,
 0.1559625734730109,
 0.1553424415003,
 0.15517288448251546,
 0.15404884978892902,
 0.1526406277181659,
 0.1526406277181659,
 0.1526406277181659,
 0.1526406277181659,
 0.1522038868295523,
 0.15042366316917008,
 0.15042366316917008,
 0.15007505629691606,
 0.14763464883937316,
 0.14763464883937316,
 0.14704292441876157,
 0.14704292441876154,
 0.14704292441876154,
 0.1454358496691159,
 0.1453095484297741,
 0.14498627873361333,
 0.1438803413133505,
 0.14349920066683505,
 0.14309095175803563,
 0.14309095175803563,
 0.14165281524036175,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14097096860865022,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.14019992744655632,
 0.1389425035941821,
 0.13812277665483924,
 0.1371182340382122,
 0.1371182340382122,
 0.13699915608779772,
 0.13699915608779772,
 0.13678822577626598,
 0.13678822577626598,
 0.13678822577626598,
 0.13678822577626598,
 0.13678822577626595,
 0.13513513513513514,
 0.13513513513513514,
 0.13513513513513514,
 0.13469012250470785,
 0.1342312110428049,
 0.1342312110428049,
 0.1342312110428049,
 0.13334518676566626,
 0.13334518676566626,
 0.13288211940534983,
 0.13181243254912406,
 0.1316245316231641,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.13151918984428584,
 0.12996881122750908,
 0.12996881122750908,
 0.12996881122750908,
 0.12996881122750908,
 0.1289651760438322,
 0.1289651760438322,
 0.1289651760438322,
 0.1289651760438322,
 0.1289651760438322,
 0.12841755074180852,
 0.1283740414907742,
 0.12734290799340264,
 0.12734290799340264,
 0.12683657235796025,
 0.12655439943366653,
 0.12655439943366653,
 0.12655439943366653,
 0.12629480039223434,
 0.12535305264097507,
 0.12535305264097507,
 0.1252721535988985,
 0.12392039927415242,
 0.12392039927415242,
 0.12329924047901797,
 0.12253577034896798,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.1221125021745327,
 0.12119654139092992,
 0.12119654139092992,
 0.1211965413909299,
 0.12006004503753284,
 0.12006004503753284,
 0.12006004503753284,
 0.11990028442779209,
 0.11990028442779209,
 0.11990028442779209,
 0.11961783342433499,
 0.1186447494690624,
 0.1186447494690624,
 0.1186447494690624,
 0.11810771907149853,
 0.11810771907149853,
 0.11810771907149853,
 0.11789662378377888,
 0.11742784807525519,
 0.11742784807525519,
 0.1162476387438193,
 0.1162476387438193,
 0.1162476387438193,
 0.1162476387438193,
 0.1162476387438193,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.11624763874381927,
 0.1144727614064285,
 0.1144727614064285,
 0.1144727614064285,
 0.1144727614064285,
 0.1144727614064285,
 0.1144727614064285,
 0.11389895949029986,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11314714296070713,
 0.11290968804428622,
 0.11290968804428622,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11277677488692017,
 0.11185934253567072,
 0.11185934253567072,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11115400287534567,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.1098436937909367,
 0.1098436937909367,
 0.1098436937909367,
 0.1098436937909367,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10887588907733556,
 0.10887588907733556,
 0.10810810810810811,
 0.10810810810810811,
 0.10810810810810811,
 0.10810810810810811,
 0.10810810810810811,
 0.10793322294408637,
 0.1076244005001263,
 0.1076244005001263,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10762440050012628,
 0.10701462561817376,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.106676149412533,
 0.1061190899945022,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853128,
 0.10529962529853126,
 0.10524566699352861,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491725,
 0.10514994558491723,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10283867552865915,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10283867552865913,
 0.10269923319261937,
 0.10269923319261937,
 0.10269923319261937,
 0.10269923319261937,
 0.10269923319261937,
 0.10228428509895357,
 0.1017387650221051,
 0.10146925788636821,
 0.10146925788636821,
 0.10146925788636821,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10067340828210367,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.10028244211278005,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09913631941932194,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09863939238321438,
 0.09802861627917438,
 0.09802861627917438,
 0.09802861627917438,
 0.09755285137982107,
 0.09755285137982107,
 0.09695723311274393,
 0.09695723311274393,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09672388203287416,
 0.09592022754223367,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.09491579957524991,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.0949157995752499,
 0.09428928580058928,
 0.09394227846020416,
 0.09394227846020416,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09320546490018,
 0.09307259888124249,
 0.09299811099505542,
 0.09299811099505542,
 0.09299811099505542,
 0.09208185110322616,
 0.09190182776172597,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09158437663089952,
 0.09133277072519848,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09119215051751065,
 0.09032775043542898,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.09004503377814962,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08948747402853657,
 0.08867021970429453,
 0.08867021970429453,
 0.08867021970429453,
 0.08867021970429453,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.0885807893036239,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.08787495503274936,
 0.0876249546540977,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08718572905786445,
 0.08710071126186844,
 0.08710071126186844,
 0.08710071126186844,
 0.08710071126186844,
 0.0863465783552691,
 0.0863465783552691,
 0.0863465783552691,
 0.0863465783552691,
 0.0863465783552691,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08585457105482137,
 0.08561170049453902,
 0.08561170049453902,
 0.08561170049453902,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08489527199560176,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08458258116519013,
 0.08419653359482289,
 0.08419653359482289,
 0.08419653359482289,
 0.08419653359482288,
 0.08419653359482288,
 0.08351476906593233,
 0.08351476906593233,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08336550215650926,
 0.08284930213349333,
 0.08284930213349333,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08156473902861858,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08108108108108109,
 0.08094446585163528,
 0.0803381317273391,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.08000711205939975,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07974522228289,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07897471897389846,
 0.07804228110385686,
 0.07802030664724674,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07767122075015,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07749842582921286,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07702442489446452,
 0.07696578428840449,
 0.07696578428840449,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477616,
 0.07610194341477615,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07543142864047142,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.07521183158458504,
 0.074458079104994,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07435223956449145,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07271792483455794,
 0.07261932421315971,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07194017065667525,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.07174960033341753,
 0.0713262951621492,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07118684968143743,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07045670884515312,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.07009996372327816,
 0.06997285579690499,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06974858324629157,
 0.06931669932133817,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06906138832741962,
 0.06893478622585808,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.0685591170191061,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06839411288813299,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140244,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06711560552140243,
 0.06650266477822091,
 0.06650266477822091,
 0.0665026647782209,
 0.0665026647782209,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06590621627456203,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06575959492214292,
 0.06532553344640132,
 0.06532553344640132,
 0.06475993376645182,
 0.06475993376645182,
 0.06475993376645182,
 0.06475993376645182,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.0644825880219161,
 0.06420877537090426,
 0.06420877537090426,
 0.06420877537090426,
 0.06367145399670132,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06327719971683327,
 0.06314740019611717,
 0.06314740019611717,
 0.06263607679944924,
 0.06263607679944924,
 0.06263607679944924,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660012,
 0.06213697660011999,
 0.06213697660011999,
 0.061649620239508984,
 0.061173554271463926,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06105625108726635,
 0.06070834938872646,
 0.06070834938872646,
 0.060536613968600245,
 0.06025359879550432,
 0.06003002251876642,

In [425]:
def recommendmovies(movie):
      movie_index= new_df[new_df['title']==movie].index[0]
      distances = similarity[movie_index]
      movies_list=sorted(list(enumerate(distances)),reverse=True, key= lambda x:x[1])[1:6]

      for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [428]:
recommendmovies("Avatar")

Titan A.E.
Small Soldiers
Independence Day
Aliens vs Predator: Requiem
Krull

In [424]:
new_df.iloc[507].title

'Independence Day'

In [429]:
import pickle

In [433]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [434]:
pickle.dump(similarity,open('similarity.pkl','wb'))